"""Maps deterministic AuditMetrics to Issues, using the exact Thai
message templates specified in Requirement.md §8. Nothing here is
generated by a model — every Issue traces back to a specific measured
field in AuditMetrics, carried in `evidence`.
"""
from __future__ import annotations

from app.schemas.audit import AuditMetrics, Issue

DEFAULT_SLOW_THRESHOLD_MS = 3000


def classify(metrics: AuditMetrics, *, slow_threshold_ms: int = DEFAULT_SLOW_THRESHOLD_MS) -> list[Issue]:
    if metrics.website_url is None:
        return [
            Issue(
                code="WEBSITE_NOT_FOUND",
                severity="opportunity",
                confidence="high",
                message_th="ไม่พบเว็บไซต์ของบริษัท",
                evidence={},
            )
        ]

    if metrics.connection_error == "DNS_ERROR" or not metrics.dns_resolved:
        return [
            Issue(
                code="DNS_ERROR",
                severity="high",
                confidence="high",
                message_th="โดเมนเว็บไซต์ไม่สามารถเข้าถึงได้",
                evidence={"website_url": metrics.website_url},
            )
        ]

    if metrics.connection_error == "CONNECTION_TIMEOUT":
        return [
            Issue(
                code="CONNECTION_TIMEOUT",
                severity="high",
                confidence="high",
                message_th="เว็บไซต์ไม่ตอบสนองหรือใช้เวลาเชื่อมต่อนานเกินไป",
                evidence={"website_url": metrics.website_url},
            )
        ]

    if metrics.connection_error == "SSL_INVALID":
        return [
            Issue(
                code="SSL_INVALID",
                severity="high",
                confidence="high",
                message_th="ใบรับรองความปลอดภัย SSL ไม่ถูกต้อง",
                evidence={"website_url": metrics.website_url},
            )
        ]

    if metrics.connection_error == "EXCESSIVE_REDIRECTS":
        return [
            Issue(
                code="EXCESSIVE_REDIRECTS",
                severity="medium",
                confidence="high",
                message_th="เว็บไซต์มีการ Redirect หลายครั้งก่อนเข้าถึงหน้าหลัก",
                evidence={"redirect_count": metrics.redirect_count},
            )
        ]

    if metrics.connection_error:
        # Any other connection-level failure we haven't specifically
        # classified — surfaced as a generic client/server error below
        # if we do have an http_status, otherwise treat as a timeout-like
        # failure so it's never silently dropped.
        if metrics.http_status is None:
            return [
                Issue(
                    code="CONNECTION_TIMEOUT",
                    severity="high",
                    confidence="medium",
                    message_th="เว็บไซต์ไม่ตอบสนองหรือใช้เวลาเชื่อมต่อนานเกินไป",
                    evidence={"connection_error": metrics.connection_error},
                )
            ]

    issues: list[Issue] = []

    if metrics.http_status is not None and 400 <= metrics.http_status < 500:
        issues.append(
            Issue(
                code="HTTP_CLIENT_ERROR",
                severity="high",
                confidence="high",
                message_th=f"เว็บไซต์พบข้อผิดพลาด HTTP {metrics.http_status}",
                evidence={"http_status": metrics.http_status},
            )
        )
    elif metrics.http_status is not None and 500 <= metrics.http_status < 600:
        issues.append(
            Issue(
                code="HTTP_SERVER_ERROR",
                severity="high",
                confidence="high",
                message_th=f"เซิร์ฟเวอร์เว็บไซต์พบข้อผิดพลาด HTTP {metrics.http_status}",
                evidence={"http_status": metrics.http_status},
            )
        )

    if metrics.https_enabled is False:
        issues.append(
            Issue(
                code="HTTPS_NOT_ENABLED",
                severity="medium",
                confidence="high",
                message_th="เว็บไซต์ยังไม่รองรับ HTTPS",
                evidence={"final_url": metrics.final_url},
            )
        )

    if metrics.ssl_valid is False:
        issues.append(
            Issue(
                code="SSL_INVALID",
                severity="high",
                confidence="high",
                message_th="ใบรับรองความปลอดภัย SSL ไม่ถูกต้อง",
                evidence={"final_url": metrics.final_url},
            )
        )

    if metrics.response_time_ms is not None and metrics.response_time_ms > slow_threshold_ms:
        seconds = round(metrics.response_time_ms / 1000, 1)
        issues.append(
            Issue(
                code="SLOW_RESPONSE",
                severity="medium",
                confidence="high",
                message_th=f"เว็บไซต์ตอบสนองช้า ใช้เวลา {seconds} วินาที",
                evidence={
                    "response_time_ms": metrics.response_time_ms,
                    "threshold_ms": slow_threshold_ms,
                },
            )
        )

    if metrics.mobile_viewport_found is False:
        # Confidence capped at medium — viewport absence alone doesn't
        # prove the site isn't responsive.
        issues.append(
            Issue(
                code="MOBILE_VIEWPORT_MISSING",
                severity="medium",
                confidence="medium",
                message_th="ไม่พบการตั้งค่าพื้นฐานสำหรับการแสดงผลบนมือถือ",
                evidence={},
            )
        )

    if metrics.title_found is False:
        issues.append(
            Issue(
                code="TITLE_MISSING",
                severity="low",
                confidence="high",
                message_th="เว็บไซต์ไม่มี Page Title",
                evidence={},
            )
        )

    if metrics.meta_description_found is False:
        issues.append(
            Issue(
                code="META_DESCRIPTION_MISSING",
                severity="low",
                confidence="high",
                message_th="เว็บไซต์ไม่มี Meta Description",
                evidence={},
            )
        )

    if metrics.contact_information_found is False:
        issues.append(
            Issue(
                code="CONTACT_INFORMATION_MISSING",
                severity="medium",
                confidence="medium",
                message_th="ไม่พบข้อมูลติดต่อที่ชัดเจนบนเว็บไซต์",
                evidence={},
            )
        )

    if metrics.contact_form_found is False:
        issues.append(
            Issue(
                code="CONTACT_FORM_MISSING",
                severity="opportunity",
                confidence="high",
                message_th="ไม่พบแบบฟอร์มสำหรับติดต่อหรือขอใบเสนอราคา",
                evidence={},
            )
        )

    if metrics.broken_link_count > 0:
        issues.append(
            Issue(
                code="BROKEN_INTERNAL_LINKS",
                severity="low",
                confidence="high",
                message_th=f"พบลิงก์ภายในเว็บไซต์ที่ใช้งานไม่ได้ {metrics.broken_link_count} รายการ",
                evidence={
                    "broken_link_count": metrics.broken_link_count,
                    "checked_link_count": metrics.checked_link_count,
                },
            )
        )

    if metrics.mixed_content_found:
        issues.append(
            Issue(
                code="MIXED_CONTENT",
                severity="medium",
                confidence="high",
                message_th="เว็บไซต์มี Mixed Content ซึ่งอาจกระทบความปลอดภัย",
                evidence={},
            )
        )

    return issues


_SEVERITY_RANK = {"critical": 0, "high": 1, "medium": 2, "low": 3, "opportunity": 4}


def build_summary(issues: list[Issue], *, max_items: int = 3) -> str:
    """A short Thai summary built only from issues actually detected —
    never a generic "perfect website" claim, since the audit is partial."""
    if not issues:
        return "ยังไม่พบปัญหาที่ชัดเจนจากการตรวจสอบเบื้องต้น"

    ranked = sorted(issues, key=lambda issue: _SEVERITY_RANK.get(issue.severity, 9))
    top_messages = [issue.message_th for issue in ranked[:max_items]]

    return " และ".join(top_messages) if len(top_messages) > 1 else top_messages[0]
